### ISSUE TITLE
Thoughts on compatibility with libusb?

### ISSUE THREAD

**Issue by xloem** [pololu/libusbp#7]
I was wondering what your thoughts were on some day offering an interface that is compatible with libusb, so that for some applications libusbp could be offered as a drop-in-replacement.

I am personally working with [libftdi](https://www.intra2net.com/en/developer/libftdi/).

What was your experience with contributing changes to libusb that you made your own library?

**Comment by DavidEGrayson** [comment]
Thank you for your interest in libusbp.  Why are you interested in using libusbp as a replacement for libusb?

For certain limited applications that connect to a non-composite USB device and only do synchronous transfers, it should be possible for someone to extend libusbp to make it act as a drop-in replacement for libusb.

I have not contributed any changes to libusb.  I mentioned an idea for an improvement [on their mailing list in 2015][1], and I got some helpful replies.

[1]: https://sourceforge.net/p/libusb/mailman/libusb-devel/thread/CAJ127Vxy4KHZUF3DQKgP4zTojcmAg2miu%2BZANZcBg9BVSEAxnw%40mail.gmail.com/#msg33894596

--David
